### ISSUE TITLE
Download link for TINU 3.0 public beta 1 (64)?

### ISSUE THREAD

**Issue by chriswayg** [ITzTravelInTime/TINU#10]
Thanks Pietro for making this nice tool, which I have been using for ages!

It has disappeared from r/hackintosh and I can't find a download link here.

**Comment by ITzTravelInTime** [comment]
It is being uploaded on mega at the moment, here is the link https://mega.nz/#!esw1HILQ!jxkMZYBLJCbvRHbRyHvYmZRKz_lw318ZNHVQAZGwgyI

And you can find it on insanelymac as well
