### ISSUE TITLE
TINU asks for GPL license agreement every time. Possible to cache this for the user?

### ISSUE THREAD

**Issue by chriswayg** [ITzTravelInTime/TINU#12]
It's a minor issue, but it's probably simple to fix. 

TINU asks to agree to the GPL license agreement every time it starts. Would it be possible to cache this for the user, so it would only ask on first use?

![image](https://user-images.githubusercontent.com/13681327/71345007-13c61d80-259f-11ea-8fdc-d0b86dd4929c.png)

**Comment by ITzTravelInTime** [comment]
this is how it's intended to work, but i may implement something like that in the future, but that will require some minor rework of the license screen's code, and it's not a priority now
