### ISSUE TITLE
Failed process

### ISSUE THREAD

**Issue by coolrecep** [ITzTravelInTime/TINU#22]
I could not create a USB on Monterey 12.0 Beta.

`[TINU] ╔═══════════════════════════════╗
[TINU] ║                               ║
[TINU] ║                               ║
[TINU] ║     _/_ o                     ║
[TINU] ║     /  , _ _   ,  ,           ║
[TINU] ║    (__(_( ( (_/(_/(__         ║
[TINU] ║    Version: RELEASE 3.0.1     ║
[TINU] ║    Build:   107               ║
[TINU] ║                               ║
[TINU] ║    Made with love using:      ║
[TINU] ║      __,                      ║
[TINU] ║     (           o  /) _/_     ║
[TINU] ║      `.  , , , ,  //  /       ║
[TINU] ║    (___)(_(_/_(_ //_ (__      ║
[TINU] ║                 /)            ║
[TINU] ║                (/             ║
[TINU] ║                               ║
[TINU] ║                               ║
[TINU] ╚═══════════════════════════════╝
 [SIP] Can't get SIP staus, due to a problem while converting the nvram output to a valid integer
 [SIP] Is SIP Enabled? We don't know because the SIP status is either unsupported or unkown.
Current user is: root
Is the current user Root?: Yes
Getting diskutil data to detect storage devices
[TINU] Got diskutil data? YES
[TINU] diskutil data successfully decoded and interpreted
[TINU] Analyzing disk data to detect usable storage devices
[TINU]     Drive: BSDID(rawValue: "disk0")
[TINU]       Drive belongs to the boot drive
[TINU]       Drive meets all the requirements
[TINU]       scanning the partitions to find usable ones:
[TINU]         Partition/Volume: BSDID(rawValue: "disk0s1")
[TINU]             Partition/Volume content: Other file system
[TINU]             Partition is not mounted, it needs to be mounted in order to be detected and usable with what we need to do later on
[TINU]         Partition/Volume: BSDID(rawValue: "disk0s2")
[TINU]             Partition/Volume content: Apple_APFS
[TINU]             Partition is a container disk, skipping it
[TINU]     Drive: BSDID(rawValue: "disk1")
[TINU]       Drive is a container drive, skipping it
[TINU]     Drive: BSDID(rawValue: "disk2")
[TINU]       Drive meets all the requirements
[TINU]       scanning the partitions to find usable ones:
[TINU]         Partition/Volume: BSDID(rawValue: "disk2s1")
[TINU]             Partition/Volume content: EFI
[TINU]             Partition is not mounted, it needs to be mounted in order to be detected and usable with what we need to do later on
[TINU]         Partition/Volume: BSDID(rawValue: "disk2s2")
[TINU]             Partition/Volume content: Apple_HFS
[TINU]             Partition meets all the requirements, it will be added to the detected partitions list as usable
[TINU]     Drive: BSDID(rawValue: "disk3")
[TINU]       Drive meets all the requirements
[TINU]       scanning the partitions to find usable ones:
[TINU]         Partition/Volume: BSDID(rawValue: "disk3s1")
[TINU]             Partition/Volume content: EFI
[TINU]             Partition is not mounted, it needs to be mounted in order to be detected and usable with what we need to do later on
[TINU]         Partition/Volume: BSDID(rawValue: "disk3s2")
[TINU]             Partition/Volume content: Apple_HFS
[TINU]             Partition meets all the requirements, it will be added to the detected partitions list as usable
[TINU]         Item type: Drive
[TINU]         Item display name is: Samsung SSD 980 PRO 500GB
[TINU]         Item type: Drive
[TINU]         Item display name is: Kingston DataTraveler 3.0
[TINU]         Item type: Partition
[TINU]         Item display name is: "Install macOS Monterey"
[TINU]         Item type: Drive
[TINU]         Item display name is: Apple UDIF salt okunur
[TINU]         Item type: Partition
[TINU]         Item display name is: Shared Support
[TINU] Trying to restore the other options to the default values
[TINU] Other options restored to the original values
[TINU] Starting Installer App scanning
[TINURecovery] Is Sandbox enabled? No
[TINURecovery] Keep in mind that this app has unrestricted access now!
[TINURecovery] Is this app/program running inside a macOS Recovery/Installer OS? No
[TINU] Scanning for usable apps in /Applications
[TINU]     /Applications/Install macOS Monterey.app has been added to the apps list
[TINU] Scanning for usable apps in /System/Applications
[TINU] Scanning for usable apps in /System/Applications
[TINU] Scanning for usable apps in /
[TINU] Scanning for usable apps in /Volumes/Big SUR - Veriler
[TINU] Scanning for usable apps in /Volumes/Big SUR - Veriler/Applications
[TINU] Scanning for usable apps in /Volumes/"Install macOS Monterey"
[TINU] Scanning for usable apps in /Applications/Utilities
[TINU] Scanning for usable apps in /System/Applications/Utilities
[TINU] Scanning for usable apps in /System/Applications/Utilities
[TINU] Scanning for usable apps in /home
[TINU] Scanning for usable apps in /usr
[TINU] Scanning for usable apps in /bin
[TINU] Scanning for usable apps in /sbin
[TINU] Scanning for usable apps in /etc
[TINU] Scanning for usable apps in /var
[TINU] Scanning for usable apps in /Library
[TINU] Scanning for usable apps in /System
[TINU] Scanning for usable apps in /private
[TINU] Scanning for usable apps in /.vol
[TINU] Scanning for usable apps in /Users
[TINU] Scanning for usable apps in /Applications
[TINU] Scanning for usable apps in /opt
[TINU] Scanning for usable apps in /dev
[TINU] Scanning for usable apps in /Volumes
[TINU] Scanning for usable apps in /tmp
[TINU] Scanning for usable apps in /cores
[TINU] Scanning for usable apps in /Volumes/Big SUR - Veriler/sw
[TINU] Scanning for usable apps in /Volumes/Big SUR - Veriler/home
[TINU] Scanning for usable apps in /Volumes/Big SUR - Veriler/usr
[TINU] Scanning for usable apps in /Volumes/Big SUR - Veriler/.Spotlight-V100
[TINU] Scanning for usable apps in /Volumes/Big SUR - Veriler/boot
[TINU] Scanning for usable apps in /Volumes/Big SUR - Veriler/Previous Content
[TINU] Scanning for usable apps in /Volumes/Big SUR - Veriler/Library
[TINU] Scanning for usable apps in /Volumes/Big SUR - Veriler/.Trashes
[TINU] Scanning for usable apps in /Volumes/Big SUR - Veriler/System
[TINU] Scanning for usable apps in /Volumes/Big SUR - Veriler/mnt
[TINU] Scanning for usable apps in /Volumes/Big SUR - Veriler/.fseventsd
[TINU] Scanning for usable apps in /Volumes/Big SUR - Veriler/private
[TINU] Scanning for usable apps in /Volumes/Big SUR - Veriler/.DocumentRevisions-V100
[TINU] Scanning for usable apps in /Volumes/Big SUR - Veriler/Users
[TINU] Scanning for usable apps in /Volumes/Big SUR - Veriler/Applications
[TINU] Scanning for usable apps in /Volumes/Big SUR - Veriler/opt
[TINU] Scanning for usable apps in /Volumes/Big SUR - Veriler/.PreviousSystemInformation
[TINU] Scanning for usable apps in /Volumes/Big SUR - Veriler/Volumes
[TINU] Scanning for usable apps in /Volumes/Big SUR - Veriler/.TemporaryItems
[TINU] Scanning for usable apps in /Volumes/Big SUR - Veriler/cores
[TINU] Scanning for usable apps in /Volumes/Big SUR - Veriler/Applications/Utilities
[TINU] Scanning for usable apps in /Volumes/"Install macOS Monterey"/.fseventsd
[TINU] Scanning for usable apps in /Volumes/"Install macOS Monterey"/.Spotlight-V100
[TINU] Installer App Scanning is complete
[TINU] Trying to restore the other options to the default values
[TINU] Other options restored to the original values
[TINU] Trying to restore the other options to the default values
[TINU] Other options restored to the original values
[TINU] Everything is ready to start the creation/installation process
[TINU] Starting the process...
[TINU] ***Trying to close conflicting processes
[TINU] If those conflicting processes are running,
[TINU] they may interfere with the success of
[TINU] the "createinstallmedia" operation
[TINU] ***No conflicting processes found or conflicting processes closed with success
[TINU] ###Trying to unmount conflicting volumes
[TINU] Those volumes may be mounted images
[TINU] from inside the macOS installer app
[TINU] and may interfere with the success of
[TINU] the "createinstallmedia" operation
[TINU]     Unmounting EFI partitions
[TINU] Unmounting all EFI partitions
[TINU] Getting diskutil data to detect storage devices
[TINU] Got diskutil data? YES
[TINU] diskutil data successfully decoded and interpreted
[TINU]       Unmounting EFI partition BSDID(rawValue: "disk2s1")
[TINU] Try to unmount the EFI partition: BSDID(rawValue: "disk2s1")
[TINU] EFI partition unmounted with success: BSDID(rawValue: "disk2s1")
[TINU]       Unmounting EFI partition BSDID(rawValue: "disk2s1") was successfoul
[TINU]       Unmounting EFI partition BSDID(rawValue: "disk3s1")
[TINU] Try to unmount the EFI partition: BSDID(rawValue: "disk3s1")
[TINU] EFI partition unmounted with success: BSDID(rawValue: "disk3s1")
[TINU]       Unmounting EFI partition BSDID(rawValue: "disk3s1") was successfoul
[TINU] All EFI partitions successfully unmounted
[TINU]     EFI partitions unmounted correctly
[TINU]     Unmounting "/Volumes/InstallESD"
[TINU]     Unmounting "/Volumes/InstallESD 2"
[TINU]     Unmounting "/Volumes/InstallESD 3"
[TINU]     Unmounting "/Volumes/InstallESD 4"
[TINU]     Unmounting "/Volumes/InstallESD 5"
[TINU]     Unmounting "/Volumes/InstallESD 6"
[TINU]     Unmounting "/Volumes/InstallESD 7"
[TINU]     Unmounting "/Volumes/InstallESD 8"
[TINU]     Unmounting "/Volumes/InstallESD 9"
[TINU]     Unmounting "/Volumes/InstallESD 10"
[TINU]     Unmounting "/Volumes/OS X InstallESD"
[TINU]     Unmounting "/Volumes/OS X InstallESD 2"
[TINU]     Unmounting "/Volumes/OS X InstallESD 3"
[TINU]     Unmounting "/Volumes/OS X InstallESD 4"
[TINU]     Unmounting "/Volumes/OS X InstallESD 5"
[TINU]     Unmounting "/Volumes/OS X InstallESD 6"
[TINU]     Unmounting "/Volumes/OS X InstallESD 7"
[TINU]     Unmounting "/Volumes/OS X InstallESD 8"
[TINU]     Unmounting "/Volumes/OS X InstallESD 9"
[TINU]     Unmounting "/Volumes/OS X InstallESD 10"
[TINU] ###Conflicting volumes unmounted with success or already unmounted
[TINU] @@@ Starting drive format process
[TINU]     The disk needs to be unmounted, in order to be formatted
[TINU] Disk that will be unmounted: disk2
[CommandSudo] Executing /usr/sbin/diskutil with args ["unmountDisk", "disk2"] with administrator privileges
[CommandSudo] Executed command: /usr/sbin/diskutil unmountDisk disk2
[CommandSudo] Exit code: 1
[CommandSudo] Output:
[CommandSudo] Error:
[CommandSudo] Unmount of disk2 failed: at least one volume could not be unmounted
[CommandSudo] Unmount was dissented by PID 257 (/System/Library/Frameworks/CoreServices.framework/Versions/A/Frameworks/Metadata.framework/Versions/A/Support/mds_stores)
[CommandSudo] Dissenter parent PPID 1 (/sbin/launchd)
[CommandSudo] Executing /usr/sbin/diskutil with args ["eraseDisk", "JHFS+", "\"Install macOS Monterey\"", "/dev/disk2"] with administrator privileges
[CommandSudo] Executed command: /usr/sbin/diskutil eraseDisk JHFS+ "Install macOS Monterey" /dev/disk2
[CommandSudo] Exit code: 0
[CommandSudo] Output:
[CommandSudo] Started erase on disk2
[CommandSudo] Unmounting disk
[CommandSudo] Creating the partition map
[CommandSudo] Waiting for partitions to activate
[CommandSudo] Formatting disk2s2 as Mac OS Extended (Journaled) with name "Install macOS Monterey"
[CommandSudo] Initialized /dev/rdisk2s2 as a 58 GB case-insensitive HFS Plus volume with a 8192k journal
[CommandSudo] Mounting disk
[CommandSudo] Finished erase on disk2
[CommandSudo] Error:
[TINU] @@@Volume format process ended with success
[TINU] The application that will be used is: /Applications/Install macOS Monterey.app
[TINU] The target drive is: /Volumes/"Install macOS Monterey"
[TINU] The script that will be performed is (including quotes): /Applications/Install macOS Monterey.app/Contents/Resources/createinstallmedia --volume /Volumes/"Install macOS Monterey" --applicationpath /Applications/Install macOS Monterey.app --nointeraction
[CommandSudo] Executing /Applications/Install macOS Monterey.app/Contents/Resources/createinstallmedia with args ["--volume", "/Volumes/\"Install macOS Monterey\"", "--applicationpath", "/Applications/Install macOS Monterey.app", "--nointeraction"] with administrator privileges
[TINU] Installer creation process started
[TINU] ******************************************
[TINU] Note that:
[TINU] -This process may take a lot of time (usually between 5 and 50 minutes) especially with slow storage devices (like Hard drives, SD/micro SD cards and virtual disks) and slow machines (like most virtual machines), so be patient and wait for it to finish
[TINU] -If you feel nothing is happening or the program is stuck remeber that TINU is just waiting for the program, createinstallmedia, to take care of the foundamental steps of this process, without knowing when it will finish his opearation. So TINU it's not stuck, it's just waiting.
[TINU] -The progress shown in the progress bar is just to give to the user the impression of busyness and that something is happening, so that's only cosmethic, but it's not actual progress since there is not a consistent way of obtaining accurate progress values during this step. TINU is just making the bar going forward by using a timer which increments it each few seconds for 50 minutes.
[TINU] -For more help or questions go to |Menu bar| -> |Help| -> |Contact us| there you will find all the links and the contacts related to this project (NOTE: this doesn't work when TINU is running in a macOS recovery environment).
[TINU] ******************************************
[TINU] Waiting for the createinstallmedia executable to finish...
[TINU] process took 18 seconds to finish
[TINU] "createinstallmedia" has finished, extracting output ...
[TINU] Output extracted: 
[TINU]       
[TINU] process error/s produced: 
[TINU]       WARNING: "--applicationpath" was deprecated in macOS 10.14, and has been removed completely in macOS 12.0.
[TINU]       Please remove it from your invocation.
[TINU]       Erasing disk: 0%... 10%...
[TINU]       Error erasing disk error number (-69888, 0)
[TINU]       An error occurred erasing the disk.
[TINU] Checking the createinstallmedia process
[TINU] Current user:                           root
[TINU] Main process exit code:                 0
[TINU] Sub process exit code produced:         252
[TINU] Probable process outcome:               Negative
[TINU] Bootable macOS installer creation failed, unknown output from "createinstallmedia" while creating the installer, please, erase this dirve with disk utility and retry
[TINU] Bootable macOS installer creation process ended
[TINU] Trying to restore the other options to the default values
[TINU] Other options restored to the original values
`

**Comment by ITzTravelInTime** [comment]
So this is not a problem with tinu, it's a problem with your usb drive which could not be formatted successfully by createinstallmedia.

Also if you are not using it, switch to the latest release because it's the only one to work properly with the new macOS.

**Comment by coolrecep** [comment]
Weird that Rufus can format it without an issue :/

**Comment by ITzTravelInTime** [comment]
it's likely something with macos here, perhaps use disk utility to erase the usb drive to macos extended journaled using the guid partition scheme, then in tinu instead of selecting the whole usb drive just select the partition you created with disk utility, also check if there are any programs using the usb drive in the background because those can mark the usb device as busy and so making the createinstallmedia format stage fail.

**Comment by ITzTravelInTime** [comment]
So any updates here? is it ok for me to close this?

**Comment by coolrecep** [comment]
Didn't have time to test again, if I can reopen the same ticket, you can close it for now 🙏
