### ISSUE TITLE
I've put my install macos xxxx.app" files elsewhere - Tinu doesn't have an option to load from non-standard lications

### ISSUE THREAD

**Issue by paul-hammant** [ITzTravelInTime/TINU#9]
Work around is to move the item back to /Applications/ then away again after using TINU.

TINU would be even better if it allowed and open dialog to navigate to another volume/dir

**Comment by ITzTravelInTime** [comment]
There is such a dialog already, pay attention to it. It is on the buttom of the window when it asks for the installer app, you can press the "Open an installer ..." button in case of no usable installer app found error, or the Open ... buttom in case it finds any apps, and then you can open any app you want using the open file dialog window provvided. By default tinu looks into the following folder: /Applications ~/Desktop ~/Downloads ~/Documents . It looks only in those folders to not waste time looking for installer apps in wired places.

So please pay more attention, the features are there.

**Comment by ITzTravelInTime** [comment]
Any new replyes? Can i close this issues?

**Comment by paul-hammant** [comment]
Nothing more from me.
